apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-todo
  namespace: project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-todo
            image: brontto/daily-todo:wge4rtes
          restartPolicy: Never