apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: string-generator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: string-generator-dep
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50