apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-ss
  namespace: project
spec:
  serviceName: mongodb-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
            claimName: mongodb-claim
      containers:
        - name: mongodb
          image: mongo
          ports:
            - name: web
              containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: mongodb
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-pass
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "bron"

        