apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: project
  name: todoserver-dep
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: todoserver
  template:
    metadata:
      labels:
        app: todoserver
    spec:
      volumes: 
        - name: shared-todo
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todoserver
          image: PROJECT/BACK-IMAGE
          volumeMounts:
          - name: shared-todo
            mountPath: /usr/src/app/files
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-pass
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "bron"
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"