apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todofront-svc
spec:
  type: NodePort
  selector: 
    app: todofront
  ports:
    - port: 2343
      protocol: TCP
      targetPort: 3000
    