apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-hash
          persistentVolumeClaim:
            claimName: string-generator-claim
      containers:
        - name: pingpong
          image: brontto/pingpong:34whras
          volumeMounts:
          - name: shared-hash
            mountPath: /usr/src/app/files
        