apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-ping
          persistentVolumeClaim:
            claimName: ping-claim
      containers:
        - name: pingpong
          image: brontto/pingpong:wegawerg
          volumeMounts:
          - name: shared-ping
            mountPath: /usr/src/app/ping
        