apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - todo_project/manifests/back-deployment.yaml
  - todo_project/manifests/front-deployment.yaml
images:
  - name: PROJECT/FRONT-IMAGE
    newName: brontto/todo_front:asdfgafsdg
  - name: PROJECT/BACK-IMAGE
    newName: brontto/todo_server:erahasdfgsdfg