apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mongodb/mongodb-volumeClaim.yaml
  - mongodb/mongodb-secret.yaml
  - mongodb/mongodb-service.yaml
  - mongodb/mongodb-statefulset.yaml
  - todo_project/manifests/persistentvolumeclaim.yaml
  - todo_project/manifests/back-deployment.yaml
  - todo_project/manifests/back-service.yaml
  - todo_project/manifests/back-horizontalpodautosacler.yaml
  - todo_project/manifests/front-deployment.yaml
  - todo_project/manifests/front-service.yaml
  - todo_project/manifests/front-horizontalpodautosacler.yaml
  - todo_project/manifests/dailyJob.yaml
  - todo_project/manifests/ingress.yaml
images:
  - name: gcr.io/PROJECT_ID/FRONT-IMAGE
    newName: brontto/todo_front:asdfgafsdg
  - name: gcr.io/PROJECT_ID/BACK-IMAGE
    newName: brontto/todo_server:erahasdfgsdfg
  - name: gcr.io/PROJECT_ID/DAILY-IMAGE
    newName: brontto/daily-todo:wge4rtes