apiVersion: v1
kind: Secret
metadata:
    name: postgress-pass
    namespace: exercises
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vcakXfttEVw=,iv:MmhaKkbzrvpt2U3XkltLYSI5Eh0aj3JugMlKc2cku4c=,tag:7TUA2l+35AeJKdaiB/QVEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kf4pxef0zdffknz2lkrmg6kjhtzpe40jz37yglppf7jqnyvr44qqr90vy8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTl3N0d1OWpSY1RKVjA1
            MVFaZUVpbUwvY0VmTlRrT3h4dHBzUEhuSlMwCiszTnVzLzBsc0ZmbVR6Q3ZpU3Nn
            eGVRKzdPUUl4MUVYN3EzQmhMQmNKWUkKLS0tIERUYnJhNEJDTElaTFlzVzJPR255
            MmFvQjUzQTBXR1l3OVNZNVBydnpFNGMK/5lRkwkIFoe9BZRv/RqwJL/Hp3vcOxfq
            SNSrRHZ9gXZ6j85exTKRyxlcDEl+mZ9B3ZPA85xGPVLDzfCD4rPCTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-24T15:45:23Z"
    mac: ENC[AES256_GCM,data:n+mcJl6RKfbKjbn0Uq76NaZDuYa7w731bMYKj+J+osW1bXakySlLFZrO1BtoBcVB0c8yw9eo5MKBU1HIiGXcKEBXFNd6jRTiEWFajgqlQnAkUtrigXsH8pwhUC1sptDm3G9/WbogcO2as6kKxeYIQ80AWSq+4rsHe51nPlPcYmo=,iv:Aq0fJZ5YuCyC5iiba3JABZ743IB+U5+Oav6IBts/x8M=,tag:w498TFMeXrYz9Ntfl9f0MQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
